# Generated by Django 4.2.14 on 2024-08-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('country', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=20)),
                ('teacher_id', models.PositiveSmallIntegerField()),
                ('hire_date', models.DateField()),
                ('teacher_contact', models.CharField(max_length=20)),
                ('teacher_gender', models.CharField(max_length=20)),
                ('specialization', models.CharField(max_length=20)),
            ],
        ),
    ]
