# Generated by Django 4.2.14 on 2024-08-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
        ('course', '0002_course_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('course', models.CharField(max_length=20)),
                ('classroom', models.CharField(max_length=20)),
                ('day_of_the_week', models.CharField(max_length=20)),
                ('coursename', models.ManyToManyField(to='course.course')),
                ('teacher', models.ManyToManyField(to='teacher.teacher')),
            ],
        ),
    ]
