# Generated by Django 4.2.14 on 2024-08-20 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
        ('student', '0002_student_course_details_alter_student_gender'),
        ('course', '0002_course_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('capacity', models.PositiveSmallIntegerField()),
                ('topics', models.EmailField(max_length=254)),
                ('number_of_groups', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=20)),
                ('courses', models.PositiveSmallIntegerField()),
                ('schedule', models.CharField(max_length=20)),
                ('artwork', models.CharField(max_length=20)),
                ('class_reperesentative', models.CharField(max_length=20)),
                ('room_number', models.PositiveSmallIntegerField()),
                ('coursename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('students', models.ManyToManyField(blank=True, related_name='classroom', to='student.student')),
                ('teacher', models.ManyToManyField(to='teacher.teacher')),
            ],
        ),
    ]
